In [10]:
import pandas as pd
df=pd.read_excel("Data_Set.xlsx")
df

,cylinders,displacement,horsepower,weight,acceleration,modelyear,maker,mpg
0,8,350,150,4699,14.5,74,America,Bad
1,8,400,170,4746,12.0,71,America,Bad
2,8,400,175,4385,12.0,72,America,Bad
3,6,250,72,3158,19.5,75,America,Bad
4,8,304,150,3892,12.5,72,America,Bad
5,8,350,145,4440,14.0,75,America,Bad
6,6,250,105,3897,18.5,75,America,Bad
7,6,163,133,3410,15.8,78,Asia,Bad
8,8,260,110,4060,19.0,77,America,Bad
9,8,305,130,3840,15.4,79,America,Bad
10,6,250,110,3520,16.4,77,America,Bad
11,6,258,95,3193,17.8,76,America,Bad
12,4,121,112,2933,14.5,72,Asia,Bad
13,6,225,105,3613,16.5,74,America,Bad
14,4,121,112,2868,15.5,73,Asia,Bad
15,6,225,95,3264,16.0,75,America,Bad
16,6,200,85,2990,18.2,79,America,Bad
17,4,121,98,2945,14.5,75,Asia,OK
18,6,232,90,3085,17.6,76,America,OK
19,4,120,97,2506,14.5,72,Europe,OK
20,4,151,85,2855,17.6,78,America,OK
21,4,116,75,2158,15.5,73,Asia,OK
22,4,119,97,2545,17.0,75,Europe,OK
23,6,146,120,2930,13.8,81,Europe,OK
24,4,116,81,2220,16.9,76,Asia,OK
25,4,156,92,2620,14.4,81,America,OK
26,4,140,88,2870,18.1,80,America,OK
27,4,97,60,1834,19.0,71,Asia,OK
28,4,134,95,2560,14.2,78,Europe,OK
29,4,97,75,2171,16.0,75,Europe,OK
30,4,97,78,1940,14.5,77,Asia,OK
31,4,98,83,2219,16.5,74,Asia,OK
32,4,79,70,2074,19.5,71,Asia,Good
33,4,91,68,1970,17.6,82,Europe,Good
34,4,89,71,1925,14.0,79,Asia,Good
35,4,83,61,2003,19.0,74,Europe,Good
36,4,112,88,2395,18.0,82,America,Good
37,4,81,60,1760,16.1,81,Europe,Good
38,4,135,84,2370,13.0,82,America,Good
39,4,105,63,2125,14.7,82,America,Good
40,4,135,84,2370,13.0,82,America,Bad
41,4,105,63,2125,14.7,82,America,Bad

In [6]:
X=df.iloc[:,:-1]
Y=df.iloc[:,7]
mak = pd.get_dummies(df['maker'],drop_first=True)
X = pd.concat([X,mak],axis=1)
X = X.drop('maker',axis=1)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.2,random_state=0)

In [9]:
from sklearn import tree
algo= tree.DecisionTreeClassifier()
algo.fit(X_train, Y_train)
Y_predict =algo.predict(X_test)
print(Y_predict)

['Good' 'Bad' 'Good' 'Bad' 'Bad' 'OK' 'OK' 'Bad' 'Good']

In [5]:
Y_test

30      OK
36    Good
27      OK
4      Bad
10     Bad
25      OK
28      OK
11     Bad
37    Good
Name: mpg, dtype: object

In [36]:
print("Naive Bayes")

Naive Bayes

In [37]:
import pandas as pd
df=pd.read_excel("Data_Set.xlsx")

In [38]:
X=df.iloc[:,:-1]
Y=df.iloc[:,7]
mak = pd.get_dummies(df['maker'],drop_first=True)
X = pd.concat([X,mak],axis=1)
X = X.drop('maker',axis=1)

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.2,random_state=0)

In [40]:
from sklearn.naive_bayes import GaussianNB
algo=GaussianNB()
algo.fit(X_train, Y_train)
Y_predict =algo.predict(X_test)
print(Y_predict)

['Good' 'Good' 'Good' 'Bad' 'Bad' 'OK' 'OK' 'Bad' 'Good']

In [30]:
#Y_test

30      OK
36    Good
27      OK
4      Bad
10     Bad
25      OK
28      OK
11     Bad
37    Good
Name: mpg, dtype: object